### ISSUE TITLE
A question on the subject of "Obsidian-minimal"

### ISSUE THREAD

**Issue by wongchenv** [kepano/obsidian-hider#1]
There is a strange problem, "Edit mode" and "browse mode", the line height is the same, but the line wrap height is different.

![image](https://user-images.githubusercontent.com/14831158/99893098-12253e00-2cb7-11eb-8927-b47ead946cc7.png)

**Comment by wongchenv** [comment]
Why is this? What should I do? Thank you

**Comment by kepano** [comment]
Please post to the forum thread
