### ISSUE TITLE
Is it possible to hide the map settings option?

### ISSUE THREAD

**Issue by i-iooi-i** [kepano/obsidian-hider#10]
![image](https://github.com/user-attachments/assets/b726d0dc-2da2-4dc7-931f-1ad410857fc2)

It doesn't seem to be very commonly used, but for the time being, it takes up an area like an in-roll ad 😂😂, and if it can be hidden, the interface will be much cleaner. Thank you so much! 💕

**Comment by kepano** [comment]
This is better handled with a snippet
