### ISSUE TITLE
Is it possible to hide the white space at the top of the page?

### ISSUE THREAD

**Issue by i-iooi-i** [kepano/obsidian-hider#9]
![image](https://github.com/user-attachments/assets/14ab5454-d7d6-47ad-ae45-d2ca9eab7d00)

I've tried a few different themes, and in reading mode there's a large area of white space at the top, and I don't know what this area is for, but it looks a little overwhelming.

**Comment by kepano** [comment]
This is outside of the scope of the plugin. It should be done using themes or snippets.
